Repository SOPT-all/35-SOPKATHON-WEB-Team1, pull requests merged in 2024-11, with the labels that each got.

#8 init/prettier,Eslint 설정
  .idea/.gitignore
  .idea/35-SOPKATHON-WEB-Team1.iml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/prettier.xml
  .idea/vcs.xml
  .prettierrc
  eslint.config.js
  package.json
  src/App.jsx
  yarn.lock
Labels: ⚙️ init

#10 init/절대경로지정
  jsconfig.json
  src/main.jsx
  vite.config.js
Labels: ⚙️ init

#11 Fix/lint 에러 해결
  src/App.jsx
  src/styles/GlobalStyle.js
Labels: 🐞fix

#14 feat/버튼 컴포넌트 생성
  src/components/common/Button/Button.jsx
  src/components/common/Button/Button.style.js
Labels: :sparkles: feat

#16 Init/axios & tanstack query 세팅
  package.json
  src/App.jsx
  src/libs/.gitkeep
  src/libs/axios.js
  yarn.lock
Labels: ⚙️ init

#21 init/ theme & GlobalStyle 변경
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: ⚙️ init

#44 feat/사용자 정보 입력 뷰 스타일 수정
  public/svg/ic_check_unfilled.svg
  public/svg/ic_check_unselect.svg
  src/assets/svg/IcCheckUnfilled.jsx
  src/assets/svg/IcCheckUnselect.jsx
  src/assets/svg/index.jsx
  src/components/common/CheckBox/CheckBox.jsx
  src/components/common/Dropdown/Dropdown.style.js
Labels: 💄style

#63 Feat/결과페이지
  src/apis/.gitkeep
  src/apis/getFortune.js
  src/assets/svg/index.jsx
  src/components/ResultPage/FortuneCard/FortuneCard.jsx
  src/components/ResultPage/FortuneCard/FortuneCard.style.js
  src/components/ResultPage/ResultFortune/ResultFortune.jsx
  src/components/common/Dropdown/Dropdown.jsx
  src/components/common/Dropdown/Dropdown.style.js
  src/constants/fortuneDummy.js
  src/hooks/.gitkeep
  src/hooks/useGetFortune.js
  src/libs/axios.js
  src/pages/LoadingPage/LoadingPage.jsx
  src/pages/ResultPage/ResultPage.jsx
  src/styles/theme.js
  src/utils/.gitkeep
  src/utils/formatDate.js
Labels: :sparkles: feat, 🚀api
